// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package licitacoesqueries

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createEdital = `-- name: CreateEdital :one
INSERT INTO editais (tenant_id, number, agency, object_description, opening_date, estimated_value, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, number, agency, object_description, opening_date, status, estimated_value, created_at, updated_at, deleted_at, created_by
`

type CreateEditalParams struct {
	TenantID          uuid.UUID      `json:"tenant_id"`
	Number            string         `json:"number"`
	Agency            string         `json:"agency"`
	ObjectDescription string         `json:"object_description"`
	OpeningDate       time.Time      `json:"opening_date"`
	EstimatedValue    sql.NullString `json:"estimated_value"`
	Status            string         `json:"status"`
	CreatedBy         uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) CreateEdital(ctx context.Context, arg CreateEditalParams) (Editai, error) {
	row := q.db.QueryRowContext(ctx, createEdital,
		arg.TenantID,
		arg.Number,
		arg.Agency,
		arg.ObjectDescription,
		arg.OpeningDate,
		arg.EstimatedValue,
		arg.Status,
		arg.CreatedBy,
	)
	var i Editai
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Number,
		&i.Agency,
		&i.ObjectDescription,
		&i.OpeningDate,
		&i.Status,
		&i.EstimatedValue,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createProposta = `-- name: CreateProposta :one
INSERT INTO propostas (tenant_id, edital_id, submitted_value, submission_date, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, edital_id, submitted_value, submission_date, status, created_at, updated_at, deleted_at, created_by
`

type CreatePropostaParams struct {
	TenantID       uuid.UUID     `json:"tenant_id"`
	EditalID       uuid.UUID     `json:"edital_id"`
	SubmittedValue string        `json:"submitted_value"`
	SubmissionDate sql.NullTime  `json:"submission_date"`
	Status         string        `json:"status"`
	CreatedBy      uuid.NullUUID `json:"created_by"`
}

func (q *Queries) CreateProposta(ctx context.Context, arg CreatePropostaParams) (Proposta, error) {
	row := q.db.QueryRowContext(ctx, createProposta,
		arg.TenantID,
		arg.EditalID,
		arg.SubmittedValue,
		arg.SubmissionDate,
		arg.Status,
		arg.CreatedBy,
	)
	var i Proposta
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EditalID,
		&i.SubmittedValue,
		&i.SubmissionDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getResultado = `-- name: GetResultado :one
SELECT id, tenant_id, edital_id, proposta_id, won, notes, created_at, updated_at, deleted_at, created_by FROM resultados
WHERE tenant_id = $1 AND edital_id = $2 AND deleted_at IS NULL LIMIT 1
`

type GetResultadoParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	EditalID uuid.UUID `json:"edital_id"`
}

func (q *Queries) GetResultado(ctx context.Context, arg GetResultadoParams) (Resultado, error) {
	row := q.db.QueryRowContext(ctx, getResultado, arg.TenantID, arg.EditalID)
	var i Resultado
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EditalID,
		&i.PropostaID,
		&i.Won,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listEditais = `-- name: ListEditais :many
SELECT id, tenant_id, number, agency, object_description, opening_date, status, estimated_value, created_at, updated_at, deleted_at, created_by FROM editais
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY opening_date DESC
`

func (q *Queries) ListEditais(ctx context.Context, tenantID uuid.UUID) ([]Editai, error) {
	rows, err := q.db.QueryContext(ctx, listEditais, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Editai
	for rows.Next() {
		var i Editai
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Number,
			&i.Agency,
			&i.ObjectDescription,
			&i.OpeningDate,
			&i.Status,
			&i.EstimatedValue,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPropostas = `-- name: ListPropostas :many
SELECT id, tenant_id, edital_id, submitted_value, submission_date, status, created_at, updated_at, deleted_at, created_by FROM propostas
WHERE tenant_id = $1 AND edital_id = $2 AND deleted_at IS NULL
ORDER BY submission_date DESC
`

type ListPropostasParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	EditalID uuid.UUID `json:"edital_id"`
}

func (q *Queries) ListPropostas(ctx context.Context, arg ListPropostasParams) ([]Proposta, error) {
	rows, err := q.db.QueryContext(ctx, listPropostas, arg.TenantID, arg.EditalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Proposta
	for rows.Next() {
		var i Proposta
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EditalID,
			&i.SubmittedValue,
			&i.SubmissionDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerResultado = `-- name: RegisterResultado :one
INSERT INTO resultados (tenant_id, edital_id, proposta_id, won, notes, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, edital_id) 
DO UPDATE SET 
    proposta_id = EXCLUDED.proposta_id, 
    won = EXCLUDED.won, 
    notes = EXCLUDED.notes, 
    updated_at = NOW()
RETURNING id, tenant_id, edital_id, proposta_id, won, notes, created_at, updated_at, deleted_at, created_by
`

type RegisterResultadoParams struct {
	TenantID   uuid.UUID      `json:"tenant_id"`
	EditalID   uuid.UUID      `json:"edital_id"`
	PropostaID uuid.NullUUID  `json:"proposta_id"`
	Won        bool           `json:"won"`
	Notes      sql.NullString `json:"notes"`
	CreatedBy  uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) RegisterResultado(ctx context.Context, arg RegisterResultadoParams) (Resultado, error) {
	row := q.db.QueryRowContext(ctx, registerResultado,
		arg.TenantID,
		arg.EditalID,
		arg.PropostaID,
		arg.Won,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Resultado
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EditalID,
		&i.PropostaID,
		&i.Won,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}
