// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package licitacoesqueries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEdital(ctx context.Context, arg CreateEditalParams) (Editai, error)
	CreateProposta(ctx context.Context, arg CreatePropostaParams) (Proposta, error)
	GetResultado(ctx context.Context, arg GetResultadoParams) (Resultado, error)
	ListEditais(ctx context.Context, tenantID uuid.UUID) ([]Editai, error)
	ListPropostas(ctx context.Context, arg ListPropostasParams) ([]Proposta, error)
	RegisterResultado(ctx context.Context, arg RegisterResultadoParams) (Resultado, error)
}

var _ Querier = (*Queries)(nil)
