// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package crmqueries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (tenant_id, related_to_type, related_to_id, type, description, due_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, related_to_type, related_to_id, type, description, due_date, status, created_at, updated_at, deleted_at, created_by
`

type CreateActivityParams struct {
	TenantID      uuid.UUID      `json:"tenant_id"`
	RelatedToType string         `json:"related_to_type"`
	RelatedToID   uuid.UUID      `json:"related_to_id"`
	Type          string         `json:"type"`
	Description   sql.NullString `json:"description"`
	DueDate       sql.NullTime   `json:"due_date"`
	CreatedBy     uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.TenantID,
		arg.RelatedToType,
		arg.RelatedToID,
		arg.Type,
		arg.Description,
		arg.DueDate,
		arg.CreatedBy,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RelatedToType,
		&i.RelatedToID,
		&i.Type,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (tenant_id, name, email, phone, document_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, email, phone, document_id, created_at, updated_at, deleted_at, created_by
`

type CreateCustomerParams struct {
	TenantID   uuid.UUID      `json:"tenant_id"`
	Name       string         `json:"name"`
	Email      sql.NullString `json:"email"`
	Phone      sql.NullString `json:"phone"`
	DocumentID sql.NullString `json:"document_id"`
	CreatedBy  uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.DocumentID,
		arg.CreatedBy,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.DocumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (tenant_id, title, customer_id, value, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, title, customer_id, status, value, created_at, updated_at, deleted_at, created_by
`

type CreateLeadParams struct {
	TenantID   uuid.UUID      `json:"tenant_id"`
	Title      string         `json:"title"`
	CustomerID uuid.NullUUID  `json:"customer_id"`
	Value      sql.NullString `json:"value"`
	Status     string         `json:"status"`
	CreatedBy  uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error) {
	row := q.db.QueryRowContext(ctx, createLead,
		arg.TenantID,
		arg.Title,
		arg.CustomerID,
		arg.Value,
		arg.Status,
		arg.CreatedBy,
	)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.CustomerID,
		&i.Status,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createOpportunity = `-- name: CreateOpportunity :one
INSERT INTO opportunities (tenant_id, lead_id, customer_id, stage, amount, expected_close_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, lead_id, customer_id, stage, amount, expected_close_date, created_at, updated_at, deleted_at, created_by
`

type CreateOpportunityParams struct {
	TenantID          uuid.UUID     `json:"tenant_id"`
	LeadID            uuid.NullUUID `json:"lead_id"`
	CustomerID        uuid.UUID     `json:"customer_id"`
	Stage             string        `json:"stage"`
	Amount            string        `json:"amount"`
	ExpectedCloseDate sql.NullTime  `json:"expected_close_date"`
	CreatedBy         uuid.NullUUID `json:"created_by"`
}

func (q *Queries) CreateOpportunity(ctx context.Context, arg CreateOpportunityParams) (Opportunity, error) {
	row := q.db.QueryRowContext(ctx, createOpportunity,
		arg.TenantID,
		arg.LeadID,
		arg.CustomerID,
		arg.Stage,
		arg.Amount,
		arg.ExpectedCloseDate,
		arg.CreatedBy,
	)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LeadID,
		&i.CustomerID,
		&i.Stage,
		&i.Amount,
		&i.ExpectedCloseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, tenant_id, related_to_type, related_to_id, type, description, due_date, status, created_at, updated_at, deleted_at, created_by FROM activities
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY due_date ASC
`

func (q *Queries) ListActivities(ctx context.Context, tenantID uuid.UUID) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, listActivities, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RelatedToType,
			&i.RelatedToID,
			&i.Type,
			&i.Description,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, tenant_id, name, email, phone, document_id, created_at, updated_at, deleted_at, created_by FROM customers
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListCustomers(ctx context.Context, tenantID uuid.UUID) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.DocumentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeads = `-- name: ListLeads :many
SELECT id, tenant_id, title, customer_id, status, value, created_at, updated_at, deleted_at, created_by FROM leads
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListLeads(ctx context.Context, tenantID uuid.UUID) ([]Lead, error) {
	rows, err := q.db.QueryContext(ctx, listLeads, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lead
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.CustomerID,
			&i.Status,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpportunities = `-- name: ListOpportunities :many
SELECT id, tenant_id, lead_id, customer_id, stage, amount, expected_close_date, created_at, updated_at, deleted_at, created_by FROM opportunities
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListOpportunities(ctx context.Context, tenantID uuid.UUID) ([]Opportunity, error) {
	rows, err := q.db.QueryContext(ctx, listOpportunities, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Opportunity
	for rows.Next() {
		var i Opportunity
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.LeadID,
			&i.CustomerID,
			&i.Stage,
			&i.Amount,
			&i.ExpectedCloseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
