// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package crmqueries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateLead(ctx context.Context, arg CreateLeadParams) (Lead, error)
	CreateOpportunity(ctx context.Context, arg CreateOpportunityParams) (Opportunity, error)
	ListActivities(ctx context.Context, tenantID uuid.UUID) ([]Activity, error)
	ListCustomers(ctx context.Context, tenantID uuid.UUID) ([]Customer, error)
	ListLeads(ctx context.Context, tenantID uuid.UUID) ([]Lead, error)
	ListOpportunities(ctx context.Context, tenantID uuid.UUID) ([]Opportunity, error)
}

var _ Querier = (*Queries)(nil)
