// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package billingqueries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID            uuid.UUID      `json:"id"`
	TenantID      uuid.UUID      `json:"tenant_id"`
	RelatedToType string         `json:"related_to_type"`
	RelatedToID   uuid.UUID      `json:"related_to_id"`
	Type          string         `json:"type"`
	Description   sql.NullString `json:"description"`
	DueDate       sql.NullTime   `json:"due_date"`
	Status        string         `json:"status"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
	CreatedBy     uuid.NullUUID  `json:"created_by"`
}

type Customer struct {
	ID         uuid.UUID      `json:"id"`
	TenantID   uuid.UUID      `json:"tenant_id"`
	Name       string         `json:"name"`
	Email      sql.NullString `json:"email"`
	Phone      sql.NullString `json:"phone"`
	DocumentID sql.NullString `json:"document_id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	CreatedBy  uuid.NullUUID  `json:"created_by"`
}

type Documento struct {
	ID            uuid.UUID     `json:"id"`
	TenantID      uuid.UUID     `json:"tenant_id"`
	RelatedToType string        `json:"related_to_type"`
	RelatedToID   uuid.UUID     `json:"related_to_id"`
	FileName      string        `json:"file_name"`
	FileUrl       string        `json:"file_url"`
	UploadedAt    time.Time     `json:"uploaded_at"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
	DeletedAt     sql.NullTime  `json:"deleted_at"`
	CreatedBy     uuid.NullUUID `json:"created_by"`
}

type Editai struct {
	ID                uuid.UUID      `json:"id"`
	TenantID          uuid.UUID      `json:"tenant_id"`
	Number            string         `json:"number"`
	Agency            string         `json:"agency"`
	ObjectDescription string         `json:"object_description"`
	OpeningDate       time.Time      `json:"opening_date"`
	Status            string         `json:"status"`
	EstimatedValue    sql.NullString `json:"estimated_value"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	CreatedBy         uuid.NullUUID  `json:"created_by"`
}

type Lead struct {
	ID         uuid.UUID      `json:"id"`
	TenantID   uuid.UUID      `json:"tenant_id"`
	Title      string         `json:"title"`
	CustomerID uuid.NullUUID  `json:"customer_id"`
	Status     string         `json:"status"`
	Value      sql.NullString `json:"value"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	CreatedBy  uuid.NullUUID  `json:"created_by"`
}

type Opportunity struct {
	ID                uuid.UUID     `json:"id"`
	TenantID          uuid.UUID     `json:"tenant_id"`
	LeadID            uuid.NullUUID `json:"lead_id"`
	CustomerID        uuid.UUID     `json:"customer_id"`
	Stage             string        `json:"stage"`
	Amount            string        `json:"amount"`
	ExpectedCloseDate sql.NullTime  `json:"expected_close_date"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
	DeletedAt         sql.NullTime  `json:"deleted_at"`
	CreatedBy         uuid.NullUUID `json:"created_by"`
}

type Plan struct {
	ID        uuid.UUID     `json:"id"`
	Name      string        `json:"name"`
	Code      string        `json:"code"`
	MaxUsers  int32         `json:"max_users"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	CreatedBy uuid.NullUUID `json:"created_by"`
}

type Proposta struct {
	ID             uuid.UUID     `json:"id"`
	TenantID       uuid.UUID     `json:"tenant_id"`
	EditalID       uuid.UUID     `json:"edital_id"`
	SubmittedValue string        `json:"submitted_value"`
	SubmissionDate sql.NullTime  `json:"submission_date"`
	Status         string        `json:"status"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	DeletedAt      sql.NullTime  `json:"deleted_at"`
	CreatedBy      uuid.NullUUID `json:"created_by"`
}

type Resultado struct {
	ID         uuid.UUID      `json:"id"`
	TenantID   uuid.UUID      `json:"tenant_id"`
	EditalID   uuid.UUID      `json:"edital_id"`
	PropostaID uuid.NullUUID  `json:"proposta_id"`
	Won        bool           `json:"won"`
	Notes      sql.NullString `json:"notes"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	CreatedBy  uuid.NullUUID  `json:"created_by"`
}

type Subscription struct {
	ID        uuid.UUID     `json:"id"`
	TenantID  uuid.UUID     `json:"tenant_id"`
	PlanID    uuid.UUID     `json:"plan_id"`
	Status    string        `json:"status"`
	StartDate time.Time     `json:"start_date"`
	EndDate   sql.NullTime  `json:"end_date"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	CreatedBy uuid.NullUUID `json:"created_by"`
}

type SystemLog struct {
	ID        uuid.UUID     `json:"id"`
	TenantID  uuid.NullUUID `json:"tenant_id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Action    string        `json:"action"`
	Timestamp time.Time     `json:"timestamp"`
}

type Tenant struct {
	ID        uuid.UUID     `json:"id"`
	Name      string        `json:"name"`
	Slug      string        `json:"slug"`
	Status    string        `json:"status"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	CreatedBy uuid.NullUUID `json:"created_by"`
}

type TenantMember struct {
	ID        uuid.UUID     `json:"id"`
	TenantID  uuid.UUID     `json:"tenant_id"`
	UserID    uuid.UUID     `json:"user_id"`
	Role      string        `json:"role"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	CreatedBy uuid.NullUUID `json:"created_by"`
}

type TenantModule struct {
	ID         uuid.UUID     `json:"id"`
	TenantID   uuid.UUID     `json:"tenant_id"`
	ModuleName string        `json:"module_name"`
	IsActive   bool          `json:"is_active"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
	DeletedAt  sql.NullTime  `json:"deleted_at"`
	CreatedBy  uuid.NullUUID `json:"created_by"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	Status       string         `json:"status"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	CreatedBy    uuid.NullUUID  `json:"created_by"`
}
