// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package billingqueries

import (
	"context"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (tenant_id, plan_id, status, start_date, created_by)
VALUES ($1, $2, $3, NOW(), $4)
RETURNING id, tenant_id, plan_id, status, start_date, end_date, created_at, updated_at, deleted_at, created_by
`

type CreateSubscriptionParams struct {
	TenantID  uuid.UUID     `json:"tenant_id"`
	PlanID    uuid.UUID     `json:"plan_id"`
	Status    string        `json:"status"`
	CreatedBy uuid.NullUUID `json:"created_by"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.TenantID,
		arg.PlanID,
		arg.Status,
		arg.CreatedBy,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PlanID,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getTenantActiveModules = `-- name: GetTenantActiveModules :many
SELECT module_name FROM tenant_modules
WHERE tenant_id = $1 AND is_active = true AND deleted_at IS NULL
`

func (q *Queries) GetTenantActiveModules(ctx context.Context, tenantID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTenantActiveModules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var module_name string
		if err := rows.Scan(&module_name); err != nil {
			return nil, err
		}
		items = append(items, module_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, code, max_users, created_at, updated_at, deleted_at, created_by FROM plans
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.QueryContext(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.MaxUsers,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
