// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package billingqueries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	GetTenantActiveModules(ctx context.Context, tenantID uuid.UUID) ([]string, error)
	ListPlans(ctx context.Context) ([]Plan, error)
}

var _ Querier = (*Queries)(nil)
