// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package systemlogsqueries

import (
	"context"
)

type Querier interface {
	CreateLog(ctx context.Context, arg CreateLogParams) error
	ListTenantLogs(ctx context.Context, arg ListTenantLogsParams) ([]SystemLog, error)
}

var _ Querier = (*Queries)(nil)
