// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package systemlogsqueries

import (
	"context"

	"github.com/google/uuid"
)

const createLog = `-- name: CreateLog :exec
INSERT INTO system_logs (tenant_id, user_id, action)
VALUES ($1, $2, $3)
`

type CreateLogParams struct {
	TenantID uuid.NullUUID `json:"tenant_id"`
	UserID   uuid.NullUUID `json:"user_id"`
	Action   string        `json:"action"`
}

func (q *Queries) CreateLog(ctx context.Context, arg CreateLogParams) error {
	_, err := q.db.ExecContext(ctx, createLog, arg.TenantID, arg.UserID, arg.Action)
	return err
}

const listTenantLogs = `-- name: ListTenantLogs :many
SELECT id, tenant_id, user_id, action, timestamp FROM system_logs
WHERE tenant_id = $1
ORDER BY timestamp DESC
LIMIT $2 OFFSET $3
`

type ListTenantLogsParams struct {
	TenantID uuid.NullUUID `json:"tenant_id"`
	Limit    int32         `json:"limit"`
	Offset   int32         `json:"offset"`
}

func (q *Queries) ListTenantLogs(ctx context.Context, arg ListTenantLogsParams) ([]SystemLog, error) {
	rows, err := q.db.QueryContext(ctx, listTenantLogs, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemLog
	for rows.Next() {
		var i SystemLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Action,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
