// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tenantqueries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	SoftDeleteTenant(ctx context.Context, id uuid.UUID) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
}

var _ Querier = (*Queries)(nil)
