// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package tenantqueries

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, status, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, status, created_at, updated_at, deleted_at, created_by
`

type CreateTenantParams struct {
	Name      string        `json:"name"`
	Slug      string        `json:"slug"`
	Status    string        `json:"status"`
	CreatedBy uuid.NullUUID `json:"created_by"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.CreatedBy,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, status, created_at, updated_at, deleted_at, created_by FROM tenants
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, status, created_at, updated_at, deleted_at, created_by FROM tenants
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTenant = `-- name: SoftDeleteTenant :exec
UPDATE tenants
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteTenant, id)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET name = $2, slug = $3, status = $4, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, status, created_at, updated_at, deleted_at, created_by
`

type UpdateTenantParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Slug   string    `json:"slug"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Status,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}
