// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package authqueries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTenantMember(ctx context.Context, arg CreateTenantMemberParams) (TenantMember, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserTenants(ctx context.Context, userID uuid.UUID) ([]GetUserTenantsRow, error)
}

var _ Querier = (*Queries)(nil)
