// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package authqueries

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTenantMember = `-- name: CreateTenantMember :one
INSERT INTO tenant_members (tenant_id, user_id, role, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, role, created_at, updated_at, deleted_at, created_by
`

type CreateTenantMemberParams struct {
	TenantID  uuid.UUID     `json:"tenant_id"`
	UserID    uuid.UUID     `json:"user_id"`
	Role      string        `json:"role"`
	CreatedBy uuid.NullUUID `json:"created_by"`
}

func (q *Queries) CreateTenantMember(ctx context.Context, arg CreateTenantMemberParams) (TenantMember, error) {
	row := q.db.QueryRowContext(ctx, createTenantMember,
		arg.TenantID,
		arg.UserID,
		arg.Role,
		arg.CreatedBy,
	)
	var i TenantMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, first_name, last_name, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, password_hash, first_name, last_name, status, created_at, updated_at, deleted_at, created_by
`

type CreateUserParams struct {
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	Status       string         `json:"status"`
	CreatedBy    uuid.NullUUID  `json:"created_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Status,
		arg.CreatedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, first_name, last_name, status, created_at, updated_at, deleted_at, created_by FROM users
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, status, created_at, updated_at, deleted_at, created_by FROM users
WHERE email = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getUserTenants = `-- name: GetUserTenants :many
SELECT t.id, t.name, t.slug, t.status, t.created_at, t.updated_at, t.deleted_at, t.created_by, tm.role 
FROM tenants t
JOIN tenant_members tm ON t.id = tm.tenant_id
WHERE tm.user_id = $1 AND t.deleted_at IS NULL AND tm.deleted_at IS NULL
`

type GetUserTenantsRow struct {
	ID        uuid.UUID     `json:"id"`
	Name      string        `json:"name"`
	Slug      string        `json:"slug"`
	Status    string        `json:"status"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
	CreatedBy uuid.NullUUID `json:"created_by"`
	Role      string        `json:"role"`
}

func (q *Queries) GetUserTenants(ctx context.Context, userID uuid.UUID) ([]GetUserTenantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTenants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTenantsRow
	for rows.Next() {
		var i GetUserTenantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
